[package]
name = "todo-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
config = "0.13.1"
diesel = "2.0.1"
log = "0.4.0"
env_logger = "0.8.3"
simplelog = "0.9.0"
fern = "0.6.0"
chrono = "0.4.19"