version: "3.8"

services:
  rust-app:
    container_name: rust-app
    build: .
    tty: true
    volumes:
      - ../todo-benchmark:/work/app
    ports:
      - 8080:8080
    # networks:
    #   - rust-app-net
  postgresql:
    image: postgres:14
    container_name: postgresql
    ports:
      - "5430:5432"
    volumes:
      - ./script:/docker-entrypoint-initdb.d
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABSE: todo
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: Passw0rd
    restart: always

volumes:
  db-store:

# networks:
#   rust-app-net:
#     driver: bridge