version: "3.8"
services:
  rust-app:
    container_name: rust-app
    build: .
    tty: true
    volumes:
      - ../todo_app_benchmarks:/work/app
    ports:
      - 8080:8080
    networks:
      - todo-app
  postgresql:
    image: postgres:14
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=developer
      - POSTGRES_DB=todo
    restart: always
    networks:
      - todo-app
volumes:
  db-store:
networks:
  # $ docker network create todo-app
  todo-app:
    external: true